name: odc-ssh-mapping
channels:
  - menpo
  - conda-forge
  - pyviz
  - anaconda
  - defaults
dependencies:
  - basemap
  - xarray
  - zarr
  - cython
  - numpy
  - matplotlib
  - gcsfs 
  - geoviews==1.6.6
  - cftime==1.1.2
  - holoviews
  - bokeh
  - dask
  - numpy
  - netCDF4
  - scipy
  - pandas
  - cartopy
  - gcsfs
  - hvplot
  - pyinterp
  - xrft
  - tabulate
  - pip
  - pip:
    - fasteners==0.15
    - monotonic==1.5
    - numcodecs==0.6.4
    - opencv-python==4.2.0.34
    - polygon3==3.0.8
    - pyeddytracker==3.0.0
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
